[2022-03-23 09:54:59,492] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: s3_big5.s3hook_readkey manual__2022-03-23T09:54:58.263272+00:00 [queued]>
[2022-03-23 09:54:59,512] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: s3_big5.s3hook_readkey manual__2022-03-23T09:54:58.263272+00:00 [queued]>
[2022-03-23 09:54:59,513] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:54:59,513] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-23 09:54:59,514] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-23 09:54:59,534] {taskinstance.py:1264} INFO - Executing <Task(PythonOperator): s3hook_readkey> on 2022-03-23 09:54:58.263272+00:00
[2022-03-23 09:54:59,541] {standard_task_runner.py:52} INFO - Started process 3194 to run task
[2022-03-23 09:54:59,548] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 's3_big5', 's3hook_readkey', 'manual__2022-03-23T09:54:58.263272+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/s3_big5.py', '--cfg-path', '/tmp/tmp7g6vwghf', '--error-file', '/tmp/tmpp_ds2_k7']
[2022-03-23 09:54:59,549] {standard_task_runner.py:77} INFO - Job 40: Subtask s3hook_readkey
[2022-03-23 09:54:59,627] {logging_mixin.py:109} INFO - Running <TaskInstance: s3_big5.s3hook_readkey manual__2022-03-23T09:54:58.263272+00:00 [running]> on host c15ce74e6b9e
[2022-03-23 09:54:59,712] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_big5
AIRFLOW_CTX_TASK_ID=s3hook_readkey
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T09:54:58.263272+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-23T09:54:58.263272+00:00
[2022-03-23 09:54:59,729] {base_aws.py:190} INFO - Credentials retrieved from login
[2022-03-23 09:55:01,328] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_big5.py", line 12, in _s3hook_readkey
    file_content = s3.read_key(key, bucket)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 62, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 355, in read_key
    return obj.get()['Body'].read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
[2022-03-23 09:55:01,428] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=s3_big5, task_id=s3hook_readkey, execution_date=20220323T095458, start_date=20220323T095459, end_date=20220323T095501
[2022-03-23 09:55:01,517] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task s3hook_readkey
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/s3_big5.py", line 12, in _s3hook_readkey
    file_content = s3.read_key(key, bucket)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 62, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 90, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 355, in read_key
    return obj.get()['Body'].read().decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa7 in position 0: invalid start byte
[2022-03-23 09:55:01,579] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-03-23 09:55:01,699] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
